[package]
name = "tetris"
version = "0.1.0"
authors = ["Fahad Saleh <ecsumed@yahoo.com>"]

[dependencies]
stdweb = "0.4.7"
# rand = "0.6"

# [dependencies.rand]
# git = "https://github.com/rust-random/rand"
# features = [
#   "wasm-bindgen",
# ]

